# Builds Modules/Expedition/AbilityData.lua: the spells each enemy can cast,
# by its npc id, from the VMaNGOS world database (https://github.com/vmangos/core,
# GPL-2.0). The game keeps an enemy's casts secret from addons, so the journal
# can't learn them by watching (Josh 2026-09-30).
#
#   gh release download db_latest -R vmangos/core -p "db-sqlite-*.zip"
#   unzip db-sqlite-*.zip
#   python scripts/make-abilities.py sqlite-dump/mangos.sqlite
#
# An enemy's spells are its spell list (creature_template.spell_list_id ->
# creature_spells) and every spell its event AI casts (creature_ai_events ->
# creature_ai_scripts, command 15). Enemies run by the server's own C++ scripts,
# most dungeon bosses among them, are not in either and get no list.
#
# Only the ids are kept. The game has every spell's name, picture and
# description, and BeebMod asks it for them, so a spell Forever doesn't have
# is dropped in game (Modules/Expedition/Journal.lua, J.Abilities).
import re
import sqlite3
import sys
from datetime import date

PASSIVE, HIDDEN = 0x40, 0x80
CAST_SPELL = 15
# effects the database lists that nobody sees cast: procs, visuals, triggers
NOT_SEEN = re.compile(r"\bDND\b|visual|trigger|transform|channeling|particles|proc\b|passive|"
                      r"random aggro|root self|self stun|despawn|becomes visible|zero mana|^clone$|"
                      r"^spawn |zzold|forsaken skills|selection", re.I)

db = sqlite3.connect(sys.argv[1])

# the latest row of each creature and spell (both have one per patch)
creatures = {}
for entry, list_id in db.execute("select entry, spell_list_id from creature_template order by patch"):
    creatures[entry] = list_id
spells = {}
for entry, name, attr in db.execute("select entry, name, attributes from spell_template order by build"):
    spells[entry] = (name, attr)

cols = ", ".join(f"spellId_{i}" for i in range(1, 9))
lists = {r[0]: [x for x in r[1:] if x] for r in db.execute(f"select entry, {cols} from creature_spells")}

casts = {}
for sid, command, spell in db.execute("select id, command, datalong from creature_ai_scripts"):
    if command == CAST_SPELL and spell:
        casts.setdefault(sid, []).append(spell)
ai = {}
for npc, a1, a2, a3 in db.execute(
        "select creature_id, action1_script, action2_script, action3_script from creature_ai_events"):
    for a in (a1, a2, a3):
        ai.setdefault(npc, []).extend(casts.get(a, ()))


def shown(spell):
    s = spells.get(spell)
    return s is not None and not (s[1] & (PASSIVE | HIDDEN)) and not NOT_SEEN.search(s[0])


out = {}
for npc, list_id in creatures.items():
    ids, names = [], set()
    for spell in lists.get(list_id, []) + ai.get(npc, []):
        # two ranks of one spell are one ability
        if shown(spell) and spells[spell][0] not in names:
            names.add(spells[spell][0])
            ids.append(spell)
    if ids:
        out[npc] = ids

lines = [
    "-- The spells each enemy can cast, by its npc id: from the VMaNGOS world",
    "-- database (https://github.com/vmangos/core), under the GPL 2.0 licence.",
    f"-- GENERATED by scripts/make-abilities.py on {date.today().isoformat()}; do not edit.",
    "local _, BT = ...",
    "BT.ExpeditionAbilities = {",
]
for npc in sorted(out):
    lines.append("\t[%d] = { %s }," % (npc, ", ".join(str(s) for s in out[npc])))
lines.append("}")
open("Modules/Expedition/AbilityData.lua", "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print(f"{len(out)} enemies, {sum(len(v) for v in out.values())} abilities")
